site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /

image:
    resource: "@SiteBundle/Controller/ImageController.php"
    type:     annotation
    prefix:   /image


admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin