services:

    helper_twig_extension:
        class: HelperExtension
        tags: [{ name: 'twig.extension' }]
        arguments: [@service_container ]


    site.upload.listener:
        class: SiteBundle\EventListener\UploadListener
        arguments: [@vich_uploader.metadata_reader, @jms_serializer, @kernel]
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate, alias: site_pre_update, priority: -1 }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist, alias: site_pre_update, priority: -1 }

    site.admin.good:
        class: SiteBundle\Admin\GoodAdmin
        arguments: [~, SiteBundle\Entity\Good, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Good }

    site.admin.price:
        class: SiteBundle\Admin\PriceAdmin
        arguments: [~, SiteBundle\Entity\Price, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Price }
